name: Python package CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .  # Installs fewsxml from the root

    - name: Install test package
      run: |
        pip install ./tests

    - name: Run tests
      run: |
        python tests/run_tests.py
      working-directory: tests

    - name: Check for errors
      run: |
        if grep -q "Error" log_oneline.txt; then
          echo "Tests failed"
          exit 1
        fi
      working-directory: tests

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts-${{ matrix.python-version }}
        path: |
          tests/log.txt
          tests/log_oneline.txt
          tests/run_dir_tmp/
